apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: caller
  namespace: grpc-mesh-demo
spec:
  to:
    kind: Service
    name: caller
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None