FROM registry.access.redhat.com/ubi9/go-toolset:latest AS build
WORKDIR /src

COPY go.mod go.sum ./
COPY gen ./gen
COPY callee ./callee

RUN go mod download

RUN mkdir -p /tmp/out && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /tmp/out/callee ./callee

FROM registry.access.redhat.com/ubi9/ubi-micro:latest
WORKDIR /
COPY --from=build /tmp/out/callee /callee

USER 1001
EXPOSE 50051
ENTRYPOINT ["/callee"]