apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: istio
spec:
  version: v1.27.5
  namespace: istio-system
  profile: ambient
  values:
    pilot:
      env:
        PILOT_ENABLE_AMBIENT: "true"