apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-discovery: enabled
    openshift.io/user-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
  labels:
    istio-discovery: enabled
    openshift.io/user-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztunnel
  labels:
    istio-discovery: enabled
    openshift.io/user-monitoring: "true"