apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gw
  namespace: grpc-mesh-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - route-purple-jellyfish-grpc-mesh-demo.apps.snoaxolab.axodevelopment.dev
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: caller-vs
  namespace: grpc-mesh-demo
spec:
  hosts:
  - route-purple-jellyfish-grpc-mesh-demo.apps.snoaxolab.axodevelopment.dev
  gateways:
  - public-gw
  http:
  - match:
    - uri:
        prefix: /call
    route:
    - destination:
        host: caller.grpc-mesh-demo.svc.cluster.local
        port:
          number: 8080